name: Check Termin Availability

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  check_termin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        env:
          DISPLAY: :99  # headless Chromium may expect a display
        run: |
          which chromium-browser || which chromium
          chromium-browser --version || chromium --version
          python check.py  # change to your actual script filename
