name: Check Termin Availability

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 30 minutes

jobs:
  check_termin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies (Chromium)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome || true

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        run: |
          python your_script.py  # change this to your actual script filename
