name: Keep Render App Awake

on:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Ping every 30 seconds for 15 minutes
        run: curl https://your-app.onrender.com